export { getFromCart } from './cart/getFromCart'
export { addToCart } from './cart/addToCart'
export { incDescQuantity } from './cart/incDescQuantity'
export { removeFromCart } from './cart/removeFromCart'
export { getFromWishlist } from './wishlist/getFromWishlist'
export { addToWishlist } from './wishlist/addToWishlist'
export { removeFromWishlist } from './wishlist/removeFromWishlist'
