export { categoriesReducer } from './categories/categoriesReducer'
export { productsReducer } from './products/productsReducer'
export { filterReducer } from './filter/filterReducer'
export { authReducer } from './auth/authReducer'
export { cartReducer } from './cart/cartReducer'
export { wishlistReducer } from './wishlist/wishlistReducer'
